spring:
  application:
    name: tarea-climalert

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    base-url: ${WEATHER_API_BASE_URL}
    key: ${WEATHER_API_KEY}
    ubicacion: ${WEATHER_API_UBICACION}

alertas:
  emails:
    - ${ALERTA_EMAIL_1}
    - ${ALERTA_EMAIL_2}
    - ${ALERTA_EMAIL_3}